name: zyalog
description: "ZyaLog - Kelola jadwal kuliah dan tugas dengan mudah."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP Client
  http: ^1.2.1

  # Local Storage
  shared_preferences: ^2.3.2

  # State Management
  provider: ^6.1.2

  # Google Fonts (Poppins)
  google_fonts: ^6.2.1

  # Date Formatting (Indonesian locale)
  intl: ^0.19.0

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
